name       : qt-creator
version    : 4.4.0
release    : 9
source     :
    - https://github.com/qtproject/qt-creator/archive/v4.4.0.tar.gz : fda24482a72446947260031b339340cce893cd6ff7bf98b1106230f78af1fb75
license    : GPL-3.0
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
