name       : qt-creator
version    : 4.0.3
release    : 1
source     :
    - https://github.com/qtproject/qt-creator/archive/v4.0.3.tar.gz : c9483c7a55d11bc1de9a668500e71b05ca33419ca14e592712e5825211ca03ca
license    : GPL-3.0
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gl)
setup      : |
    qmake -r 
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    install -Dm644 $pkgfiles/qtcreator.desktop $installdir/usr/share/applications/qtcreator.desktop

