name       : qt-creator
version    : 10.0.0
release    : 48
source     :
    - https://download.qt.io/official_releases/qtcreator/10.0/10.0.0/qt-creator-opensource-src-10.0.0.tar.xz : 9489829de05893a4628b7b6581af096c48afbd31c932cd8a4db30a90c52197bf
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(yaml-cpp)
    - designer6
rundeps    :
    - qt6-base-devel
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DCMAKE_INSTALL_LIBDIR=$(basename %libdir%) \
        -DPYTHON_EXECUTABLE=$(which python3)
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Not in ypkg yet. https://github.com/getsolus/ypkg/pull/22/files
    # %qml6_cache
