name       : qt-creator
version    : 4.11.2
release    : 30
source     :
    - https://download.qt.io/official_releases/qtcreator/4.11/4.11.2/qt-creator-opensource-src-4.11.2.tar.xz : 8d67e45b66944fdb0f879cbfae341af7e38d6a348cf18332b5cb9f07937aae02
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - qt5-quickcontrols
    - syntax-highlighting-devel
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %patch -p1 < $pkgfiles/qtcreator-preload-plugins.patch
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
