name       : qt-creator
version    : 4.12.3
release    : 31
source     :
    - https://download.qt.io/official_releases/qtcreator/4.12/4.12.3/qt-creator-opensource-src-4.12.3.tar.xz : 81e12010aace162755f3a94ff788f7973f7a902ac1a9bc968f30e535cf5da32a
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - qt5-quickcontrols
    - syntax-highlighting-devel
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
