name       : qt-creator
version    : 4.13.2
release    : 33
source     :
    - https://download.qt.io/official_releases/qtcreator/4.13/4.13.2/qt-creator-opensource-src-4.13.2.tar.xz : b00a5c13ba67d2e3436e6d9bf32fba38d780a1de0bc85b813daac672021e9428
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - qt5-quickcontrols
    - syntax-highlighting-devel
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
