name       : qt-creator
version    : 4.2.2
release    : 5
source     :
    - https://github.com/qtproject/qt-creator/archive/v4.2.2.tar.gz : 1ec52b3df2be16c3167e3ef1be230be8a11af4682de2371133c5b3236db96aa5
license    : GPL-3.0
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    install -Dm00644 $pkgfiles/qtcreator.desktop $installdir/usr/share/applications/qtcreator.desktop
