name       : qt-creator
version    : 4.10.2
release    : 28
source     :
    - https://download.qt.io/official_releases/qtcreator/4.10/4.10.2/qt-creator-opensource-src-4.10.2.tar.xz : 9add6bdddfe5726bb02535409c2ed788b1afeee082121f54f887281d0e3c449a
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
clang: yes
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - qt5-quickcontrols
    - syntax-highlighting-devel
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %patch -p1 < $pkgfiles/qtcreator-preload-plugins.patch
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
