name       : qt-creator
version    : 4.6.2
release    : 16
source     :
    - https://download.qt.io/official_releases/qtcreator/4.6/4.6.2/qt-creator-opensource-src-4.6.2.tar.xz : bbaf667f51051c602df02e04c1d7369bef9553326d8377bc36a019ae718843cc
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - qt5-quickcontrols
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
