name       : qt-creator
version    : 4.5.0
release    : 11
source     :
    - https://github.com/qtproject/qt-creator/archive/v4.5.0.tar.gz : 4823ea99d0de4ceac329882c7e68c3573e0eeb32ea826ce0c01c36442c91d1aa
license    : GPL-3.0
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    cd $installdir; qml_cache
