name       : qt-creator
version    : 4.4.1
release    : 10
source     :
    - https://github.com/qtproject/qt-creator/archive/v4.4.1.tar.gz : 1fb7c84d6be9dbb4be75fb3170c4ba3fa74de1a4c34ad3efe8a6177ee2e6e515
license    : GPL-3.0
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
