name       : qt-creator
version    : 4.8.1
release    : 19
source     :
    - https://download.qt.io/official_releases/qtcreator/4.8/4.8.1/qt-creator-opensource-src-4.8.1.tar.xz : 8f691de9b30b99dd44e010525ba9bf3054142a1082dc5273c46c533b91c07bd9
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - qt5-quickcontrols
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
