name       : qt-creator
version    : 4.15.2
release    : 38
source     :
    - https://download.qt.io/official_releases/qtcreator/4.15/4.15.2/qt-creator-opensource-src-4.15.2.tar.xz : 9edb911d910665891a8e1488d72d080fb9a6002b24eb9034aa031a67a5496f7f
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - qt5-quickcontrols
    - syntax-highlighting-devel
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
