name       : qt-creator
version    : 5.0.3
release    : 39
source     :
    - https://download.qt.io/official_releases/qtcreator/5.0/5.0.3/qt-creator-opensource-src-5.0.3.tar.xz : 7fd3b14310bcecee6b134f8cb7f4c0ed2385d7f4cecd48d756c5c1fd650ce2eb
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - qt5-quickcontrols
    - syntax-highlighting-devel
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
