name       : qt-creator
version    : 4.6.1
release    : 14
source     :
    - http://download.qt.io/official_releases/qtcreator/4.6/4.6.1/qt-creator-opensource-src-4.6.1.tar.xz : e74dce61becc2a97199ff4a0e50a148e4dbafb6572587212323c470d70c137da
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - qt5-quickcontrols
rundeps    :
    - qt5-base-devel
    - qt5-quickcontrols
setup      : |
    %qmake -r
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir/usr
    %qml_cache
