name       : qt-creator
version    : 7.0.0
release    : 45
source     :
    - https://download.qt.io/official_releases/qtcreator/7.0/7.0.0/qt-creator-opensource-src-7.0.0.tar.xz : d39a05e48bb961cfab61135a5ee5503fc4d381c74000b910f36bf0cea37736d9
license    : GPL-3.0-only
component  : programming.ide
summary    : IDE for Qt Development
description: |
    Qt Creator is a cross-platform IDE for development with the Qt framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(yaml-cpp)
    - designer6
rundeps    :
    - qt6-base-devel
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DCMAKE_INSTALL_LIBDIR=$(basename %libdir%) \
        -DPYTHON_EXECUTABLE=$(which python3)
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Not in ypkg yet. https://github.com/getsolus/ypkg/pull/22/files
    # %qml6_cache
